### ISSUE TITLE
Make the documentation more user-friendly

### ISSUE THREAD

**Issue by piwonskp** [NethermindEth/warp#1029]
- [ ] Remove warp 1, warp 2 comparison
- [ ] Add quickstart in place of the comparison
- [ ] Move installation and contributing from markdown files to the documentation
- [ ] The page https://nethermindeth.github.io/warp/ is redundant. The first page in the documentation should be quickstart.

**Comment by ankit7241** [comment]
Hey, I have few questions : 
1. Can I start working on this issue ?
2. By "quickstart" you mean the page : "Getting started" ? If so should I also change the title of this page from "Getting started" to "Quickstart"
3. Where should I move the file " Installation and Usage" and " Contribution Guidelines " in the docs or am I misunderstanding the 3rd point ? It would be great if you could explain the 3rd point in bit detail.

**Comment by piwonskp** [comment]
Hey @ankit7241,

1. Of course
2. Getting started is the wider section, quickstart is the quickest way of starting to work with the tool. E.g. We've got quickstart here: https://github.com/NethermindEth/warp#quickstart.
3. There is the documentation on https://nethermindeth.github.io/warp/. The source for the documentation is in [docs directory](https://github.com/NethermindEth/warp/tree/develop/docs) in the repo. We've got two installation pages, one is in markdown [here](https://github.com/NethermindEth/warp/blob/develop/installation.md), the other one is in docs. The page in the docs should be updated if needed (markdown files are newer) ie. all the needed information from installation.md and [dependencies.md](https://github.com/NethermindEth/warp/blob/develop/dependencies.md) should be there. Once it's done `installation.md` and `dependencies.md` shall be removed from the repository

**Comment by piwonskp** [comment]
Hey @ankit7241 do you plan to address the remaining comments? If not we'll try to find someone to finish the PR

**Comment by ankit7241** [comment]
> Hey @ankit7241 do you plan to address the remaining comments? If not we'll try to find someone to finish the PR

Hey @piwonskp I'll work on these changes this weekend.
