### ISSUE TITLE
Cannot install warp: Docker image?

### ISSUE THREAD

**Issue by Pet3ris** [NethermindEth/warp#165]
Hi There,

Really cool project.

I tried 3 separate ways of installing `warp`:

- Big Sur (invalid OS issue)
- In Docker (Ubuntu 18) => missing libc6 dependency, apparently only 21 has the right version
- In Docker (Ubuntu 21) => fails at `add-apt-repository ppa:deadsnakes/ppa`

Do you think it would make sense to provide a Dockerfile for reproducibility? I would happily provide one if I could get this to work.

Here's what I did, I ran the command:

```bash
docker run -it ubuntu:impish /bin/bash
```

and then followed the sequence of steps in the README order.

**Comment by murcake** [comment]
Hi, could you please see [this comment](https://github.com/NethermindEth/warp/issues/139#issuecomment-977802714) to check if it fixes the issues with MacOS? 

What is the error with adding the PPA?

Reproducibility is important, we'll think about adding a dockerfile

**Comment by BitBaseBit** [comment]
Are you on a M1 mac?

> Hi There,
> 
> Really cool project.
> 
> I tried 3 separate ways of installing `warp`:
> 
> * Big Sur (invalid OS issue)
> * In Docker (Ubuntu 18) => missing libc6 dependency, apparently only 21 has the right version
> * In Docker (Ubuntu 21) => fails at `add-apt-repository ppa:deadsnakes/ppa`
> 
> Do you think it would make sense to provide a Dockerfile for reproducibility? I would happily provide one if I could get this to work.
> 
> Here's what I did, I ran the command:
> 
> ```shell
> docker run -it ubuntu:impish /bin/bash
> ```
> 
> and then followed the sequence of steps in the README order.

Are you on an M1 Mac?

**Comment by Pet3ris** [comment]
> Hi, could you please see [this comment](https://github.com/NethermindEth/warp/issues/139#issuecomment-977802714) to check if it fixes the issues with MacOS?
> 
> What is the error with adding the PPA?
> 
> Reproducibility is important, we'll think about adding a dockerfile

Thanks! The environment flag fixed the Mac OS compatibility issue but brought another issue:

```
libc++abi.dylib: terminating with uncaught exception of type boost::wrapexcept<solidity::langutil::CompilerError>: Called compile with errors.
```

Contract compiles with solc. Here it is for reference:

```solidity
// SPDX-License-Identifier: UNLICENSED

pragma solidity ^0.8.9;

contract Warp {
        constructor() {
        }
}
```

**Comment by Pet3ris** [comment]
> > Hi There,
> > Really cool project.
> > I tried 3 separate ways of installing `warp`:
> > 
> > * Big Sur (invalid OS issue)
> > * In Docker (Ubuntu 18) => missing libc6 dependency, apparently only 21 has the right version
> > * In Docker (Ubuntu 21) => fails at `add-apt-repository ppa:deadsnakes/ppa`
> > 
> > Do you think it would make sense to provide a Dockerfile for reproducibility? I would happily provide one if I could get this to work.
> > Here's what I did, I ran the command:
> > ```shell
> > docker run -it ubuntu:impish /bin/bash
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then followed the sequence of steps in the README order.
> 
> Are you on an M1 Mac?

Intel

**Comment by Pet3ris** [comment]
> 

The PPA error was this:

```
Err:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu impish Release
  404  Not Found [IP: 91.189.95.85 80]
Hit:6 http://archive.ubuntu.com/ubuntu impish-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu impish Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by BitBaseBit** [comment]
> ```solidity
> // SPDX-License-Identifier: UNLICENSED
> 
> pragma solidity ^0.8.9;
> 
> contract Warp {
>         constructor() {
>         }
> }
> ```

@Pet3ris  Yes, you need have `pragma solidity ^0.8.x` where 0 <= x <= 6. Our solc version for generating the Yul AST is based off 0.8.7

> > 
> 
> The PPA error was this:
> 
> ```
> Err:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu impish Release
>   404  Not Found [IP: 91.189.95.85 80]
> Hit:6 http://archive.ubuntu.com/ubuntu impish-backports InRelease
> Reading package lists... Done
> E: The repository 'http://ppa.launchpad.net/deadsnakes/ppa/ubuntu impish Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```

This is expected with deadsnakes.
