### ISSUE TITLE
GLIBC_2.33 Not Found Error

### ISSUE THREAD

**Issue by hayden4r4** [NethermindEth/warp#188]
System Version: Ubuntu 20.04  
Python Version: 3.7.12  
Warp Version: 0.2.16  
GLIBC Version: 2.31 (default on Ubuntu 20.04)  

I'm receiving the following error when attempting to transpile a contract:  
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/bin/linux/kudu)

It looks like only Ubuntu version 21.04 comes with GLIBC 2.33, so looks like a docker container with 21.04 is the only way currently around this? Any other way?  Also if 21.04 is the only compatible version for transpiling it would probably be best to supply a docker container in the repo.

**Comment by BitBaseBit** [comment]
Thanks, I'm fixing this now.

**Comment by BitBaseBit** [comment]
@hayden4r4 Can you try running `make` with #191 and let me know if this fixes the issue?

**Comment by BitBaseBit** [comment]
@hayden4r4 , can you re-install Warp & try again? It should work now.

**Comment by hayden4r4** [comment]
Thanks! That fixed the issue.
