### ISSUE TITLE
No such file or directory: '_marked.sol'

### ISSUE THREAD

**Issue by hayden4r4** [NethermindEth/warp#194]
System Version: Ubuntu 20.04
Python Version: 3.7.12
sol-warp Version: 0.5.1

I am attempting to transpile a contract with the command "warp transpile ./loan.sol loan" from within the directory containing loan.sol, where loan is the name of the primary contract.  I get the following error (with full traceback):  

ERROR: Compilation failed

Traceback (most recent call last):
  File "/mnt/c/Blockchain/envs/warp/bin/warp", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/cli/warp_cli.py", line 162, in main
    warp()
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/cli/warp_cli.py", line 45, in transpile
    output = transpile_from_solidity(file_path, contract_name)
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/yul/main.py", line 77, in transpile_from_solidity
    output = get_for_contract(sol_src_path_modified, main_contract, ["abi"])
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/yul/utils.py", line 136, in get_for_contract
    get_source_version(sol_source)
  File "/mnt/c/Blockchain/envs/warp/lib/python3.7/site-packages/yul/utils.py", line 146, in get_source_version
    with open(sol_source) as f:
FileNotFoundError: [Errno 2] No such file or directory: './loan_marked.sol'

**Comment by murcake** [comment]
Hi! Are you sure that warp's version is 0.5.1? We are still on 0.2.x. 
Is it possible to take a look at the loan.sol file?

**Comment by BitBaseBit** [comment]
> Hi! Are you sure that warp's version is 0.5.1? We are still on 0.2.x. Is it possible to take a look at the loan.sol file?

@murcake , we uploaded the latest version to PyPy with the semantic fixes, so 0.5.1 is correct.

**Comment by murcake** [comment]
Oh, I see

**Comment by hayden4r4** [comment]
> Hi! Are you sure that warp's version is 0.5.1? We are still on 0.2.x. 
> 
> Is it possible to take a look at the loan.sol file?

The loan.sol file is here: https://github.com/hayden4r4/ERC20-Loan/blob/master/workspace/contracts/loan.sol

**Comment by BitBaseBit** [comment]
> > Hi! Are you sure that warp's version is 0.5.1? We are still on 0.2.x.
> > Is it possible to take a look at the loan.sol file?
> 
> @murcake ,The loan.sol file is here: https://github.com/hayden4r4/ERC20-Loan/blob/master/workspace/contracts/loan.sol

@hayden4r4 , you need to use solidity 0.8.0 <= 0.8.8

**Comment by hayden4r4** [comment]
So I tried my loan.sol file with `pragma solidity >=0.8.0 <=0.8.8;` and still getting the same error. I also tried with a simple hello world contract: `
pragma solidity >=0.8.0 <=0.8.8;

   contract test {
        string public greet = "Hello World!";
}` 
Same error also, so it doesn't seem to be a specific bug with my loan.sol contract.

**Comment by murcake** [comment]
@hayden4r4 warp uses a modified solidity compiler based on solc 0.8.9 (but we've recently upgraded it to 0.8.11), so 0.8.9 should be in the allowed range. You can use for example `pragma solidity ^0.8.6;`, that works with the test contract

**Comment by murcake** [comment]
Still, it fails on your contract with another issue, the root of which is clear and the fix is coming soon

**Comment by murcake** [comment]
And now that I've fixed that issue, I've found another one which can't be easily fixed in Warp for now :D. Your contract contains 'immutable' variables and `block.timestamp`, neither of which is yet supported by Warp.
However, you can remove `immutable` qualifier from the variables and `timestamp` is soon to be added to StarkNet, so hopefully it will work again

**Comment by hayden4r4** [comment]
@murcake awesome, the hello world contract transpiles fine using `pragma solidity ^0.8.6`.  And that is good to know, I forgot block.timestamp is not supported by starknet yet, looking forward to it being implemented.  Thanks!
