### ISSUE TITLE
File outside of allowed directories even when placed in the same directory

### ISSUE THREAD

**Issue by FawadHa1der** [NethermindEth/warp#567]
LiquidityMath.sol and Position.sol are in the same directory. 

    Position.sol:6:1: ParserError: Source "LiquidityMath.sol" not found: File outside of allowed directories.
    import './LiquidityMath.sol';
    ^---------------------------^

**Comment by GuyMcComb** [comment]
Hi There,

Could you provide some more information regarding this error? Is this related to this issue: https://github.com/NethermindEth/warp/issues/565 ?

**Comment by swapnilraj** [comment]
@FawadHa1der can you try our latest release 
https://www.npmjs.com/package/@nethermindeth/warp

I think it should fix both the issues
