### ISSUE TITLE
Unclear command 

### ISSUE THREAD

**Issue by DecentrilizedMan** [NethermindEth/warp#614]
It is not clear for me about the error message : 
```
Try using --python option for warp install to specify the path to python3.7
```
Commands that i've tried are including :  
```
warp install --python 
```
```
warp install --python3.7 
```
```
warp install --python3
```

**Comment by DecentrilizedMan** [comment]
I've tried it !
But it gets me annoying that i need to re-install it everytime i use wrap :(

GuyMcComb ***@***.***> 于2022年7月18日周一 18:05写道：

**Comment by GuyMcComb** [comment]
You shouldn't have to reinstall for every usage. 
Could you run `warp install --python <path_to_python> --verbose`?

It should give us more insight into what is going wrong.
