### ISSUE TITLE
Got CLientConnectorCertiticateError while trying to access https://alpha4.starknet.io/gateway/add_transaction.

### ISSUE THREAD

**Issue by ArturVargas** [NethermindEth/warp#689]
Environment:
  * OS: macOS Monterey v12.5.1
  * Python 3.7.9
  * Cairo version:  0.9.1
  * Warp Version: 2.1.0
 
Description:
I'm using. the example_contracts ERC20 to transpile the solidity code into cairo code, this generate a `warp_output` dir successfully with 3 files, ``ERC20__WC__WARP_abi.json``, ``ERC20__WC__WARP_compiled.json``, ``ERC20__WC__WARP.cairo`` and when I try to deploy the contract file I get this error:  

<img width="843" alt="Captura de Pantalla 2022-08-31 a la(s) 22 38 31" src="https://user-images.githubusercontent.com/21693926/188789281-ab0e6e7c-84a8-4816-815b-cf4dc635b110.png">

**Comment by GuyMcComb** [comment]
Hi There,

A new version of Warp got released last night v2.2.2. Could you attempt the same with that version?
We are aware there have been some issues with prior versions.

**Comment by ArturVargas** [comment]
Hi @GuyMcComb,
I'm update my warp version to 2.2.2 and I get a similar error
<img width="844" alt="Captura de Pantalla 2022-09-07 a la(s) 10 16 54" src="https://user-images.githubusercontent.com/21693926/188915735-4c417563-f5ac-44e3-a125-0b46effb0e9c.png">

**Comment by swapnilraj** [comment]
Hi @ArturVargas, sorry it took us a while to get your query on discord. I posted a possible solution there just today.
The problem is here how macos handles python installations, can you try the suggestion in this thread
https://github.com/Rapptz/discord.py/issues/423#issuecomment-272093801

**Comment by ArturVargas** [comment]
Thanks @swapnilraj! I'm just install the Certificates because I'm using python3.7 and that fix the issue
<img width="1116" alt="Captura de Pantalla 2022-09-07 a la(s) 11 15 01" src="https://user-images.githubusercontent.com/21693926/188928799-176dc427-b5ba-4554-8504-ecef26bd60e2.png">

**Comment by swapnilraj** [comment]
Glad that your issue was resolved @ArturVargas!
