### ISSUE TITLE
Remove warp test

### ISSUE THREAD

**Issue by swapnilraj** [NethermindEth/warp#736]
It is confusing for users of warp to have a test command which doesn't test their contracts but tests warp functionality

**Comment by JorikSchellekens** [comment]
@cicr99 @piwonskp opinion on this?

**Comment by JorikSchellekens** [comment]
@cicr99 @piwonskp opinion on this?

**Comment by piwonskp** [comment]
I agree, npm scripts are for development. User's cli shouldn't include dev commands such as test, it affects the UX.
