### ISSUE TITLE
Improve initialisation of static arrays in memory

### ISSUE THREAD

**Issue by swapnilraj** [NethermindEth/warp#821]
To initialise empty static arrays in memory we generate a function to write 0 or the default value for the type (think structs) at the right offsets in memory. For example

```
function test() external {
   uint256[100] d;
}
```

Generates a function with 100 parameters all taking a value of 0 and then it writes 0 at each index sequentially, for these cases we only need to pass one parameter and instead of writing 0 sequentially to each location we should generate a recursive function that loops through the indexes of the array to do this.

**Comment by esdras-santos** [comment]
Hi @swapnilraj, I just Warped the example function that you write above and i need to find the file that does this declaration inside the Warped contract `let (__warp_3_d) = WM1_s_arr(Uint256(low=0, high=0), Uint256(low=0, high=0), Uint256(low=0, high=0), ....` , so I'll be able change that to `let (__warp_3_d) = WM1_s_arr(size_arr);` in case of static array. Can you help me?

**Comment by swapnilraj** [comment]
> Hi @swapnilraj, I just Warped the example function that you write above and i need to find the file that does this declaration inside the Warped contract `let (__warp_3_d) = WM1_s_arr(Uint256(low=0, high=0), Uint256(low=0, high=0), Uint256(low=0, high=0), ....` , so I'll be able change that to `let (__warp_3_d) = WM1_s_arr(size_arr);` in case of static array. Can you help me?

Hey @esdras-santos those functions are being generated in the arrayLiteral file see [here](https://github.com/NethermindEth/warp/blob/develop/src/cairoUtilFuncGen/memory/arrayLiteral.ts#L109).
