### ISSUE TITLE
Make cli for deploy and declare more usable

### ISSUE THREAD

**Issue by piwonskp** [NethermindEth/warp#835]
Instead of requiring the user to pass the path to the Cairo file
warp deploy and declare should take the path to the solidity file and the contract name in the solidity file to deploy/declare

**Comment by swapnilraj** [comment]
On further thought I think with the new output structure, I don't think we should go ahead with this change.
if we make the arguments for deploy and declare of the form, `path/to/contract.sol:ContractName` then we are assuming that the user is using the `warp_output` folder. Our 'new' output format where we just recreate the Solidity file path in `warp_output` or the user specified folder; where the deepest folder contains the corresponding cairo file for each contract is good and doesn't hide anything from the user.
