### ISSUE TITLE
Example Folder Clean Up

### ISSUE THREAD

**Issue by piwonskp** [NethermindEth/warp#836]
# Example Folder Clean Up

The example folder is meant for warp users to test the functionality of warp.
Currently, we use it for tests as well, but this will interfere with the users’s experience so we should clean it up

**Comment by KhadijaKamran** [comment]
I would like to work on this issue

**Comment by piwonskp** [comment]
Great, I've assigned you the task

**Comment by JorikSchellekens** [comment]
Hey @KhadijaKamran can you detail your plan for this a bit, what kind of contracts you want to put in the examples folder?

**Comment by swapnilraj** [comment]
@KhadijaKamran are you still working on this? Do you need any pointers?

**Comment by KhadijaKamran** [comment]
I am not working on this issue. Anyone else interested can work on it.

**Comment by julio4** [comment]
@piwonskp I can work on it! 

Should we move most of the files under `exampleContracts` that are specific to a test in a new folder (e.g. `testsContracts`) ? Also, should we keep the `test:examples` script with all tests or add a new script ?

**Comment by piwonskp** [comment]
Fixed in #1018
