### ISSUE TITLE
literalExpressionEvaluator binary operations with booleans

### ISSUE THREAD

**Issue by piwonskp** [NethermindEth/warp#838]
In the literalExpressionEvaluator pass, a binary expression could be calculated at compile time, even when only one argument is a literal. In the case of a boolean literal with the `&&` operator, the following is done:

```tsx
case '&&': // false && x = false
	return notNullMember ? null : false;
```

It is also known that if `notNullMember` is `true`, the result of the operation is the other member, and so the binaryOperation expression can be replaced by the left or right expression correspondingly. This is something that could be added.

Same thing happens for `||` operator

Add tests for this behaviour

**Comment by aniket2405** [comment]
"It is also known that if `notNullMember` is `true`, the result of the operation is the other member, and so the binaryOperation expression can be replaced by the left or right expression correspondingly."

In this case, we are considering the situation when one of the expression is a null. Then, if the `notNullMember` is `true`, should the function not return `null` itself, and not the other member? Similar case for the `||` operator.

**Comment by cicr99** [comment]
No, if an expression returns `null` that doesn't mean its value is `null`, it means it wasn't possible to determine its value at compilation time. Check [evaluateLiteralExpression](https://github.com/NethermindEth/warp/blob/1af5b777f0869bf02dbe078a663b2304b2908a80/src/passes/literalExpressionEvaluator/literalExpressionEvaluator.ts#L70) function for better understanding
