### ISSUE TITLE
Duplicate Events

### ISSUE THREAD

**Issue by piwonskp** [NethermindEth/warp#842]
Given a library L and a contract C, which uses library L. 

If both L and C have the same definition for event E (not just naming, field as well ⇒ which means signature match, the other way around wouldn’t be an issue) it gets transpiled and defined twice in warped contract C ⇒ which mean compilation error.

Suggested solution: Don’t add Events to the contract from a library if they already exist in it.

Need to verify edge case what happens if the duplicate event is not defined in the contract itself, but in an ancestor. Or a library used by the library which the contract uses.

An example:

```solidity
library L {
	 event E { ... }
}

contract C {
   using L for some type;
   
	 // Same def as event E in L
   event E { ... }
}
```

After the contract is Warped:

```solidity

contract Warped_C {
   event E { ... }
   event E { ... } // Compilation error due to redefinition
}
```

**Comment by swapnilraj** [comment]
This bug was fixed in #810
