### ISSUE TITLE
Cairo Generated Function Pruner

### ISSUE THREAD

**Issue by piwonskp** [NethermindEth/warp#843]
# Cairo Generated Function Pruner

In Warp the function pruner pass removes all internal functions definitions which are not called  by any external function (be it directly or indirectly), nonetheless if any of the pruned functions it’s the only one to call a generated function, the generated function will still remain, even if it has no use. This produces unnecessary code and can be the cause of some bugs like the generated function implicits not being imported.

As a solution you should initially make the FunctionPrunner pass work at Source Unit level and not Contract level. But as you will notice that eliminating generated function definitions doesn’t stop them from being generated. The reason is they work differently and once they are created the generated code is stored and printed later, without checking if the function definition still exists.

Here are two possible solutions:

1. An ugly patchy one where you check for the generated functions definition which were deleted and erase accordingly. But this can get ugly really fast with edge cases, like generated functions which call other generated functions, and it would be overly complicated to cover all cases
2. The other way needs extensive modification, but I think the pros outweighs the cons. It’s making all generated functions a special type of `CairoFunctionDefinition` like `CairoGeneratedFunctionDefinition` , where they have properties like code, and a list of other generated functions they call. The cons are that all function generators should be modified to work like this and the cairo writer will need some modifications. The pros are you don’t need to do anything else, the already existing FunctionPrunner pass will handle which function to prune and not and also getting more internal api consistency, like if I delete a function definiton I expect for it not to be generated (which is not what’s currently happening).

**Comment by LuisLara-UH** [comment]
Hey @piwonskp could you please assign this task to me?

**Comment by piwonskp** [comment]
@LuisLara-UH done :)

**Comment by cicr99** [comment]
PR #869 should solve this issue. This PR is a restructuring of the way cairo generated functions and imports are handled, which is basically the option 2 from the description
