### ISSUE TITLE
Cache compile result during execution

### ISSUE THREAD

**Issue by piwonskp** [NethermindEth/warp#845]
If contract C is a dependency of both Contract A and Contract B, then when executing

```bash
warp transpile A.sol B.sol
```

C will get transpiled twice during transpilation of (A) and during tranpilation of (B)

**Comment by swapnilraj** [comment]
To tackle this and other issues related to compiling, Warp should create a json file with the hash of the source file tracking if the source file has changed, to avoid re-compiling everytime when the user is deploying or declaring. This json file should store other useful information like class hash of files for easy retrieving.
