### ISSUE TITLE
Update CairoWriters

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/warp#917]
For ERC20 support, prioritize updating the syntax of the output code of the following list of writers:
- [x] #926
- [x] #927
- [x] #928
- [x] #929
- [x] #930
- [x] #931
- [x] #932
- [x] #933
- [x] #934
- [x] #935
- [x] #936
- [x] #938
- [x] #937
- [x] #939
- [x] #940
- [x] #950

**Comment by LuisLara-UH** [comment]
Hey @piwonskp @cicr99 can I get assigned some writers?

**Comment by cicr99** [comment]
This issue was addressed on #983
