### ISSUE TITLE
Update Cairo generated functions code

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/warp#918]

**Comment by cicr99** [comment]
This issue is blocked by #869. Once that get merged in we can start modifying the code.

**Comment by rodrodros** [comment]
I am taking this issue alongside #921 because storage util function generators should be updated to work with the new syntax and new storage vars.  Although I will focusing mainly on the storage and not  other elements (like memory or calldata) that may require work as well

**Comment by cicr99** [comment]
This was addressed on #958 
Some errors related to this task were also addressed in #983
